### ISSUE TITLE
Connection issues with 1.21.20

### ISSUE THREAD

**Issue by CoveWolf** [MCXboxBroadcast/Broadcaster#122]
Hello! First of I just wanna say I really love this project as it really helps us console players out! I noticed on the new Minecraft update 1.21.20 that MCXboxBroadcast seems to get stuck on the "connecting to multiplayer game" screen and then never connect to the server. Eventually it will just time out after a couple of minutes or so. I was wondering if anyone else has had this issue or if it's just me. I have tried resetting the instance, relinking the account, and updating to the latest release of MCXboxBroadcast. If anyone has any insight as to what I may be doing wrong here please let me know. Thanks and have a wonderful day/night!

**Comment by rtm516** [comment]
Known issue with 1.21.20 support, hoping to push a fix soon

**Comment by ReligusPotato78** [comment]
Joining over Lan is the only thing that still works but I am having the same issue with the perpetual connecting to server issue. Eagerly look forward to the bug fix coming soon! 

[currentSessionResponse.json](https://github.com/user-attachments/files/16604871/currentSessionResponse.json)
[lastSessionResponse.json](https://github.com/user-attachments/files/16604872/lastSessionResponse.json)

Here are the dumps from a session I just tried if any of the info helps.

**Comment by superJK92iscool** [comment]
Same issue for me

**Comment by Xaidencodesshit** [comment]
Same but I get `Unable to connect to worlds`

**Comment by James-P-Bennett** [comment]
This better not be an intentional patch to block these accounts, otherwise I'm gonna go leave an upper decker at MS HQ.

**Comment by S-SHI777** [comment]
The bedrock-server.pdb file was removed in Minecraft BE v1.21.20, is that related to this issue? I would appreciate it if you could let me know.

**Comment by rtm516** [comment]
It's not related but makes it slightly harder to debug and diagnose the issue

**Comment by PoPzQ** [comment]
Pls fix😭

**Comment by Xaidencodesshit** [comment]
> This better not be an intentional patch to block these accounts, otherwise I'm gonna go leave an upper decker at MS HQ.

About this all mods on my realm stopped working and the marketplace mod was the only one working

**Comment by yisic4** [comment]
May I ask how long it will take to fix this

**Comment by onebeastchris** [comment]
at this moment, we do not know. There is no eta.

For the meantime, tell your players to use the DNS method or the app-on-your phone methods, those still work

**Comment by yisic4** [comment]
Can this error be 100% fixed? Or is there a 50% chance of fixing this error?

**Comment by rtm516** [comment]
An early preview build has been released to donators in Discord. Once everything is tidy and stable it will release publicly

**Comment by rtm516** [comment]
Builds 50+ resolve the connection issues related to 1.21.20
