### ISSUE TITLE
Friend adding bug.

### ISSUE THREAD

**Issue by HealingHalo8** [MCXboxBroadcast/Broadcaster#134]
Account does not add back after adding a couple players and it gets stuck.

Reported by a few others in the discord.

Possibly a issue with Xbox live API being down or something?

Account
![Screenshot 2024-08-22 233011](https://github.com/user-attachments/assets/6f359644-ea54-44ec-b601-7914ee7c9b0a)
![Screenshot 2024-08-22 232740](https://github.com/user-attachments/assets/91ca0869-4b09-4c41-b861-ff1e484fa936)

**Comment by rtm516** [comment]
Should be fixed in the latest donator preview
