### ISSUE TITLE
Add new branch

### ISSUE THREAD

**Issue by lolwhatdidigetbanned** [MCXboxBroadcast/Broadcaster#136]
Add new geyser extension branch :( I wanna just compile it unless u update the egg:(

**Comment by rtm516** [comment]
As stated in https://github.com/MCXboxBroadcast/Broadcaster/issues/122 the code and full public release will come once everything is sorted

**Comment by lolwhatdidigetbanned** [comment]
> As stated in #122 the code and full public release will come once everything is sorted

What about the egg? Will it be updated??? I just want that updated for the new branch playground nethernet

**Comment by lolwhatdidigetbanned** [comment]
But also when is it done

**Comment by rtm516** [comment]
Yes the Pterodactyl egg will be updated when the new version is public.

It will be done when its done.

**Comment by lolwhatdidigetbanned** [comment]
> Yes the Pterodactyl egg will be updated when the new version is public.
> 
> It will be done when its done.

Please can it be updated early? :(

**Comment by onebeastchris** [comment]
> It will be done when its done
