### ISSUE TITLE
wont connect on consle 

### ISSUE THREAD

**Issue by xlemonbarx69** [MCXboxBroadcast/Broadcaster#141]
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN Exception in thread "WebSocketConnectReadThread-221" java.lang.NoSuchFieldError: Class org.bouncycastle.asn1.bc.BCObjectIdentifiers does not have member field 'org.bouncycastle.asn1.ASN1ObjectIdentifier xmss_SHAKE128_512ph'
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder.<clinit>(Unknown Source)
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.build(Unknown Source)
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at com.rtm516.mcxboxbroadcast.core.webrtc.DtlsClient.<init>(DtlsClient.java:75)
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at com.rtm516.mcxboxbroadcast.core.webrtc.PeerSession.receiveOffer(PeerSession.java:79)
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at com.rtm516.mcxboxbroadcast.core.webrtc.RtcWebsocketClient.handleConnectRequest(RtcWebsocketClient.java:131)
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at com.rtm516.mcxboxbroadcast.core.webrtc.RtcWebsocketClient.handleDataAction(RtcWebsocketClient.java:122)
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at com.rtm516.mcxboxbroadcast.core.webrtc.RtcWebsocketClient.onMessage(RtcWebsocketClient.java:104)
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:593)
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:885)
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:819)
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379)
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216)
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:506)
30.08 07:01:28 [Server] WebSocketConnectReadThread-221/WARN at java.base/java.lang.Thread.run(Thread.java:1583)

this is what i get whenever i try to join moblie bedrock mc then it says unable to connect to world on the moblie bedrock

**Comment by rtm516** [comment]
Can you provide a geyser dump, and full server logs. Likely some other plugin is causing a problem here
