### ISSUE TITLE
Remove bot friends?

### ISSUE THREAD

**Issue by chrostino** [MCXboxBroadcast/Broadcaster#153]
I might have misunderstood how this works, but I tried running the extension using my main account and soon after a bunch of bot (I guess) accounts added me as a friend. Since then I switched to an alt account to use this extension and removed my main account from it, yet I am unable to remove the bot accounts from my friends because as soon as I remove them they add me back as a friend. How should this work?

**Comment by rtm516** [comment]
If your nolonger using you main account on the tool then it shouldn't be causing an issue.
You can force the bots to stop following you by blocking and unblocking them

**Comment by chrostino** [comment]
I don't know it's weird, they keep adding me back as a friend even when I block them, I don't even know how it's possible. Anyway thanks for the help, if the issue is not related to the extension I will try to find a solution myself
