### ISSUE TITLE
Failed to Get/Refresh Auth Token

### ISSUE THREAD

**Issue by MyriadMuffin** [MCXboxBroadcast/Broadcaster#161]
Just want to say first that I love this plugin. It makes Minecraft servers so much more versatile!

Anyways, I am getting this error for MCXboxBroadcast: 

> [18:55:10 WARN]: [Geyser-Spigot] [mcxboxbroadcast] [Auth] Failed to get/refresh auth token
> com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.responsehandler.exception.MsaRequestException: status: 400 Bad Request, error: invalid_grant, error message: The user could not be authenticated as the grant is expired. The user must sign in again.
>         at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.responsehandler.MsaResponseHandler.handleJsonError(MsaResponseHandler.java:31) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.responsehandler.JsonHttpResponseHandler.handle(JsonHttpResponseHandler.java:45) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.responsehandler.JsonHttpResponseHandler.handle(JsonHttpResponseHandler.java:30) ~[?:?]
>         at Geyser-Spigot (3).jar/net.lenni0451.commons.httpclient.HttpClient.execute(HttpClient.java:213) ~[Geyser-Spigot (3).jar:?]
>         at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.msa.StepMsaToken.execute(StepMsaToken.java:114) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.msa.StepMsaToken.refresh(StepMsaToken.java:56) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.msa.StepMsaToken.refresh(StepMsaToken.java:36) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.BiMergeStep.refresh(BiMergeStep.java:46) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.BiMergeStep.refresh(BiMergeStep.java:23) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.AbstractStep.refresh(AbstractStep.java:69) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.core.AuthManager.initialise(AuthManager.java:120) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.core.AuthManager.getXboxToken(AuthManager.java:162) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getXboxToken(SessionManagerCore.java:127) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:144) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:79) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.createSession(MCXboxBroadcastExtension.java:213) ~[?:?]
>         at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$onPostInitialize$4(MCXboxBroadcastExtension.java:185) ~[?:?]
>         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
>         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
>         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
>         at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

I don't know how to refresh the auth token without completely installing the extension and config files. Any help would be much appreciated!

**Comment by rtm516** [comment]
Delete the cache.json and then relogin but make sure to login using username and password not using any fancy no password login as that causes issues sometimes.
