### ISSUE TITLE
[FEATURE] Auto refresh xbox live token

### ISSUE THREAD

**Issue by Maxplayz7566** [MCXboxBroadcast/Broadcaster#172]
It would be nice not to re login to my Microsoft account every day so I'm wondering if this is planned or even possible in the first place. Or Its already there it just doesn't work for me.

**Comment by rtm516** [comment]
This is already part of the tool and should be working, I suggest logging into your account on xbox.com to confirm there's nothing wrong with it and make sure only the tool is logging into it and nothing else.
If there's nothing there then I would look over the server/tool logs to see if its mentioning any errors.

**Comment by Maxplayz7566** [comment]
Thanks!
