### ISSUE TITLE
Server sent broken packet

### ISSUE THREAD

**Issue by ImJTech13** [MCXboxBroadcast/Broadcaster#173]
When i connect via MCXboxBroadcast i get a "Server sent broken packet" error, if I try to rejoin it just loads infinitely. If i connect directly through the ip for geyser it works fine.

**Comment by rtm516** [comment]
Provide a `geyser dump` assuming your using the extension

**Comment by ImJTech13** [comment]
https://dump.geysermc.org/rQVAsIGWmTxDLfHTQDaR4WrfKlhkG0eJ

**Comment by rtm516** [comment]
Please update mcxboxbroadcast as your on a version that doesn't support 1.21.50

**Comment by ImJTech13** [comment]
That worked thanks!
