### ISSUE TITLE
Reauthenticate

### ISSUE THREAD

**Issue by ImJTech13** [MCXboxBroadcast/Broadcaster#174]
I had to change the password to my account that the server was connected to but now it's telling me to reauthenticate and I can't figure out how to.

**Comment by rtm516** [comment]
Delete the cache.json, restart the server then go through the normal Auth process again

**Comment by ImJTech13** [comment]
That worked but the cache.json file hasn't been resaved

**Comment by ImJTech13** [comment]
So I have to reauthenticate every time I want to use the server

**Comment by rtm516** [comment]
Are there any errors in the log? After every auth the cache.json should be saved, if its not then likely something is preventing it

**Comment by ImJTech13** [comment]
<img width="1030" alt="Screen Shot 2024-12-15 at 10 10 25 AM" src="https://github.com/user-attachments/assets/95fbeb6a-3bce-4da3-93d2-f29f0e51572e" />

**Comment by rtm516** [comment]
Delete your config

**Comment by ImJTech13** [comment]
That worked! Thanks!
