### ISSUE TITLE
cannot join the server using friends anymore

### ISSUE THREAD

**Issue by Paceski** [MCXboxBroadcast/Broadcaster#177]
https://paste.md-5.net/edahuwejov.cs

**Comment by Paceski** [comment]
Joining with add server works fine.

**Comment by Paceski** [comment]
Could be related to this, posting this here just incase

![image](https://github.com/user-attachments/assets/535134cb-8777-4509-a51d-a8c02f63d7aa)

**Comment by Paceski** [comment]
https://support.xbox.com/en-US/xbox-live-status

**Comment by Paceski** [comment]
But I guess that's for destiny only?

**Comment by rtm516** [comment]
It looks like xbox live service is now restored, also updated some internals to smooth out joining. Please update to build 69.
