### ISSUE TITLE
 Unable to connect to world

### ISSUE THREAD

**Issue by TutorialMan7727** [MCXboxBroadcast/Broadcaster#178]
![image](https://github.com/user-attachments/assets/b4bf4bd1-7fa0-4a71-bf23-78be2044bb5c)
Cant join server when tyring to join from the freinds menu. Note this server has just started using this

**Comment by Paceski** [comment]
Having the same issue, could be something related to xbox.

**Comment by TutorialMan7727** [comment]
shows  limited https://support.xbox.com/en-US/xbox-live-status

**Comment by rtm516** [comment]
It looks like service is now restored, also updated some internals to smooth out joining. Please update to build 69.

**Comment by TutorialMan7727** [comment]
Thanks
