### ISSUE TITLE
Auto-Login Feature for Docker Setup

### ISSUE THREAD

**Issue by AltSystem42** [MCXboxBroadcast/Broadcaster#179]
I'm thrilled with how well this setup works—huge thanks to everyone who has contributed to it! I was wondering if there's a way to enable an auto-login feature for the account. Occasionally, power outages in my area cause the server to reboot, and while Docker Compose successfully relaunches the program, it prompts me to log in again. Is there a way to automate this process, or is it exclusive to the paid manager?

**Comment by rtm516** [comment]
That sounds like you haven't mounted the config/cache files into the container so they are getting deleted and recreated with the container.
Please share your compose yml if you are still having issues.

**Comment by AltSystem42** [comment]
> That sounds like you haven't mounted the config/cache files into the container so they are getting deleted and recreated with the container. Please share your compose yml if you are still having issues.

You are correct. Still an amateur at docker lol. Thank you! ^_^

**Comment by rtm516** [comment]
No worries, also I suggest using the discord linked in the readme. I will likely respond quicker for things like this.
